### PR TITLE
Add unique field prevalidation

### LINKED ISSUE #11: Pre-validate uniqueness.
Eg. If `username` is a unique field, then `User.objects.create(username=...)` should ideally:

* Run inside a transaction.
* Run a query to check no existing username already exists. Raise an exception otherwise.
* Perform the insert.

This is far more helpful than raising an integrity error.

### PR DESCRIPTION
**Pull request by florimondmanca**
Fixes #11 

TBH, looking at the implementation I was thinking this could be something that `typesystem` could provide a framework for.

For example, provide hook method such as `async def validate_unique_field(name, value):`, which wouldn't to anything by default, and allow `Schema` subclasses (`Model` in this case) to override it to perform any calls required to check the uniqueness constraint.

### CODE REVIEW

**Comment by tomchristie** [comment]
> For example, provide hook method

Indeed, yup. Also really we'll want to make sure that any uniqueness errors are included alongside any other errors, rather than only running uniqueness validation once everything else passes.

Will need to think about this one a bit.

**Comment by tomchristie** [comment]
Plus we'll want to include the same validation on `update` too, but excluding `pk=instance.pk`

**Comment by florimondmanca** [comment]
@tomchristie I added uniqueness validation in `.update()` too. The way I did it was to create a subclass of `typesystem.Object` which allows to see how the "hook" thing could look. :-) All errors are now returned as one exception too.

**Comment by florimondmanca** [comment]
Hi @tomchristie, I realize this PR has been around for a while — are there any blockers here? I suppose the fact that this PR works around TypeSystem not providing async validation may be one. Happy to receive any pointers on how to tackle/clean this up, either here on in TypeSystem.

**Pull request closed without merging**
